version: '2'
services:
  mysql:
    image: mysql:8
    hostname: mysql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./schema:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_HOST=%